### PR TITLE
ext/openssl/ossl_pkey.c: fix build with libressl >= 3.5.0

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with libressl >= 3.5.0:

```
ossl_pkey.c: In function 'ossl_pkey_export_traditional':
ossl_pkey.c:681:62: error: invalid use of incomplete typedef 'EVP_PKEY' {aka 'struct evp_pkey_st'}
  681 |  EVP_PKEY_asn1_get0_info(NULL, NULL, NULL, NULL, &aname, pkey->ameth);
      |                                                              ^~
```

Fixes:
 - http://autobuild.buildroot.org/results/9b2622fbc4c2c2b787578ee83fc6a23795a84415

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by hsbt** [comment]
Can you submit this to [ustream](https://github.com/ruby/openssl)? Thanks.

**Comment by jeremyevans** [comment]
No need to submit this upstream, as I fixed this upstream in https://github.com/ruby/openssl/pull/506.  We just haven't updated the openssl gem in the ruby repository since Christmas.
