### PR TITLE
Update default gems for Ruby 3.1

### PR DESCRIPTION
**Pull request by hsbt**
https://bugs.ruby-lang.org/issues/18992

### CODE REVIEW

**Comment by hsbt** [comment]
csv-3.2.4 used `sub_test_case`. We need to pick this methods from https://github.com/test-unit/test-unit/blob/master/lib/test/unit/testcase.rb#L421

I try to pick them. But It's not working like this.

```
# Running tests:

[109/955] #<Class:0x00000001037a7c78>#test_integer_float = 0.00 s
  1) Error:
#<Class:0x00000001037a7c78>#test_integer_float:
NoMethodError: undefined method `convert' for nil:NilClass
    /Users/hsbt/Documents/github.com/ruby/ruby/test/csv/parse/test_convert.rb:40:in `test_integer_float'
(snip)
```

@kou Do you have any idea without picking it or give advice for above failure?

**Comment by kou** [comment]
Ah, sorry. csv should not use `sub_test_case` then. I'll change tests in csv.

csv tests in ruby/ruby use https://github.com/ruby/ruby/tree/master/tool/test, right?

**Comment by kou** [comment]
Could you try csv 3.2.5?

**Comment by hsbt** [comment]
> csv tests in ruby/ruby use https://github.com/ruby/ruby/tree/master/tool/test, right?

Yes, it is. and Ruby test suite includes https://github.com/ruby/ruby/blob/master/tool/lib/core_assertions.rb for `assert_separatedly` mainly.

I removed `Minitest` namespace from ruby test suite. So we can migrate to `test-unit` + `core_assertions.rb`. But It's out of scope this PR.

**Comment by kou** [comment]
> I removed Minitest namespace from ruby test suite. So we can migrate to test-unit + core_assertions.rb. But It's out of scope this PR.

OK. We can discuss it in RubyKaigi 2022. I'll go to Mie.

**Comment by hsbt** [comment]
@kou Thanks! csv-3.2.5 is working with Ruby 3.1.x.

**Review by nagachika — APPROVED** [review]
